version: '3'

services:
  api:
    container_name: auth-api
    volumes:
      - ./:/auth-app
    ports:
      - 8008:8008
    build: .
    restart: always
    command: >
     bash -c "python manage.py runserver 0.0.0.0:8008"